import React from 'react';

const stories = [
  {
    id: 1,
    location: 'Kyoto, Japan',
    title: 'Whispers of the Bamboo Forest',
    snippet: 'The air grew still as I stepped into Arashiyama. Sunlight, filtered through a thousand green stalks, danced on the path. It felt like walking through a living cathedral, each creak of bamboo a prayer to ancient spirits...',
    imageUrl: 'https://picsum.photos/seed/kyotostory/800/600',
  },
  {
    id: 2,
    location: 'Patagonia, Argentina',
    title: 'The Glacier\'s Song',
    snippet: 'Perito Moreno groaned, a deep, primal sound that vibrated through my bones. A skyscraper of ice calved from its face, crashing into the turquoise water. It was a brutal, beautiful symphony of nature\'s power...',
    imageUrl: 'https://picsum.photos/seed/patagoniastory/800/600',
  },
  {
    id: 3,
    location: 'Cairo, Egypt',
    title: 'Sunrise Over Giza',
    snippet: 'The first rays of dawn painted the Great Pyramid in hues of gold and rose. From my viewpoint, the city was a distant murmur. Here, only the silent gaze of the Sphinx and the weight of 4,500 years of history existed...',
    imageUrl: 'https://picsum.photos/seed/cairostory/800/600',
  }
];

const TravelStories: React.FC = () => {
  return (
    <section id="stories" className="py-20 bg-gray-900/50 overflow-hidden">
      <div className="container mx-auto px-4">
        <div className="text-center mb-12">
            <h3 className="text-3xl md:text-5xl font-bold bg-gradient-to-r from-emerald-400 to-white bg-clip-text text-transparent">AI-Powered Travel Stories</h3>
            <p className="text-gray-400 mt-2 max-w-2xl mx-auto">Discover destinations through immersive narratives generated by our AI.</p>
        </div>
        <div className="relative">
          {/* Fix: Changed '-ms-overflow-style' to 'msOverflowStyle' to comply with React's camelCase style properties. */}
          <div className="flex gap-8 pb-8 -mx-4 px-4 overflow-x-auto" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
            {stories.map((story, index) => (
              <div key={story.id} className="group flex-shrink-0 w-[90vw] md:w-1/2 lg:w-1/3 animate-fadeInUp" style={{ animationDelay: `${index * 150}ms`, opacity: 0 }}>
                <div className="relative bg-black rounded-lg shadow-lg overflow-hidden h-full transform transition-transform duration-500 hover:scale-105">
                  <img src={story.imageUrl} alt={story.title} className="w-full h-56 object-cover" />
                  <div className="p-6">
                    <p className="text-sm font-semibold text-emerald-400">{story.location}</p>
                    <h4 className="text-xl font-bold mt-1 text-white">{story.title}</h4>
                    <p className="text-gray-400 mt-3 text-sm">{story.snippet}</p>
                  </div>
                   <div className="absolute inset-0 border-2 border-transparent group-hover:border-emerald-500 rounded-lg transition-all duration-300 pointer-events-none"></div>
                </div>
              </div>
            ))}
          </div>
           <div className="absolute top-0 right-0 h-full w-16 bg-gradient-to-l from-gray-900/50 to-transparent pointer-events-none md:hidden"></div>
           <div className="absolute top-0 left-0 h-full w-16 bg-gradient-to-r from-gray-900/50 to-transparent pointer-events-none md:hidden"></div>
        </div>
      </div>
    </section>
  )
}

export default TravelStories;